### ISSUE TITLE
Set Cursor Pos does nothing ?

### ISSUE THREAD

**Issue by Zardoz89** [MadMockers/BareBonesOS#11]
Or I'm doing something very wrong, or there is a bug on SetCursorPos. Code : 

```
  SET PUSH, 1
  SET PUSH, 1
  INT 0x1001       ; Set cursor at 1,1
  ADD SP, 2       ; clean up stack
```

Does nothing.
Perhaps, my bbos.bin is corrupted, but I can write to screen and read chars from keyboard without any issue.

The whole source code : https://github.com/Zardoz89/fun-with-dcpu-16/blob/develop/test.dasm

**Comment by MadMockers** [comment]
Should be:

```
  SET A, 0x1001
  SET PUSH, 1
  SET PUSH, 1
  INT 0x4743       ; Set cursor at 1,1
  ADD SP, 2       ; clean up stack
```

**Comment by Zardoz89** [comment]
Really, some one should kill me.....
